exports.seed = function (knex, Promise) {
  return knex('todos').insert([
    {
      title: 'Go to gym',
      description: 'leg and abs day',
      user_id: 1,
      important: true,
      completed: true,
      date_time: Date(),
    },
    {
      title: 'Go to supermarket',
      description: 'need to get produce',
      user_id: 1,
      important: false,
      completed: false,
      date_time: Date(),
    },
    {
      title: 'Do Laundry',
      user_id: 1,
      important: true,
      completed: false,
      date_time: Date(),
    },
    {
      title: 'Go to the park',
      description: 'get some basketball practice in',
      user_id: 2,
      important: true,
      completed: true,
      date_time: Date(),
    },
    {
      title: 'Buy some baking supplie',
      user_id: 2,
      important: true,
      completed: false,
      date_time: Date(),
    },
    {
      title: 'Go for a run',
      description: '20 min run at night',
      user_id: 2,
      important: true,
      completed: false,
      date_time: Date(),
    },
    {
      title: 'submit retro',
      description: 'by 6pm',
      user_id: 3,
      important: true,
      completed: true,
      date_time: Date(),
    },
    {
      title: 'join group stand up',
      user_id: 3,
      important: true,
      completed: false,
      date_time: Date(),
    },
    {
      title: 'work on bw project',
      description: 'finish todos model',
      user_id: 3,
      important: true,
      completed: true,
      date_time: Date(),
    },
    {
      title: 'Meet up with Kate',
      description: 'in the morning',
      user_id: 4,
      important: false,
      completed: true,
      date_time: Date(),
    },
    {
      title: 'work on the redux udemy project',
      user_id: 4,
      important: true,
      completed: true,
      date_time: Date(),
    },
  ])
  // add data into insert
}
